version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: pocDB
      POSTGRES_USER: pocUser
      POSTGRES_PASSWORD: poc123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  saisiedetemps:
    build:
      context: ./backend
    environment:
      - SERVER_PORT=$SERVER_PORT
      - ACTIVE_PROFILE=$ACTIVE_PROFILE
    ports:
      - 3000:$SERVER_PORT
    depends_on:
      - postgres

volumes:
  postgres_data:
